# Generated by Django 3.2.5 on 2022-12-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('h_index', models.IntegerField()),
                ('n_pubs', models.IntegerField()),
                ('n_citations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ManyToManyField(through='paper.Paper_Author', to='paper.Author'),
        ),
    ]
