# Generated by Django 3.2.5 on 2022-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paper',
            name='doc_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='isbn',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='issn',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='issue',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='lang',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='n_citation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='page_end',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='page_start',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='pdf',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paper',
            name='publisher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='volume',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.ManyToManyField(to='paper.Keyword'),
        ),
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.ManyToManyField(to='paper.Url'),
        ),
        migrations.AddField(
            model_name='paper',
            name='venue',
            field=models.ManyToManyField(to='paper.Venue'),
        ),
    ]
