# Generated by Django 3.2.5 on 2022-12-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='author',
            new_name='authors',
        ),
    ]
